# Workflow to run on each PR 

name: PR Quality

on:
  push:
    branches: [ main, 'feature/*', 'refactor/*', 'hotfix/*', 'bug/*', 'release/*' ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_output.outputs.status }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Lint
        id: lint
        continue-on-error: false
        run: ./gradlew lintKotlin --no-daemon

      - name: Run tests
        id: tests
        continue-on-error: false
        if: steps.lint.outcome == 'success'
        run: |
          ./gradlew clean testDevDebugUnitTest --no-daemon --no-build-cache

      - name: set output
        id: set_output
        if: always()
        run: echo ::set-output name=status::${{ job.status }}
